### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by Fangwq** [mfinzi/residual-pathway-priors#9]
Hi, I read your paper recently and I am confused about the following equation in the paper:
```
\[Sigma]^2 I = \[Sigma]^2 QQ^T + \[Sigma]^2 PP^T.
```
Since `Q` is an orthogonal matrix, why is this equation correct? Thank you very much!

**Comment by mfinzi** [comment]
Hi @Fangwq 
$Q \in \mathbb{R}^{d \times r}$ has orthogonal columns, but it's less than full dimensional due to the dimension of the equivariant subspace $Q^TQ =I_{r\times r}$ but $QQ^T\ne I_{d\times d}$
Does that answer your question?

**Comment by Fangwq** [comment]
Thank you for your clarification!
